# Generated by Django 6.0.1 on 2026-02-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('immatriculation', models.CharField(max_length=20)),
                ('nom_chauffeur', models.CharField(max_length=30)),
                ('note', models.TextField(default=None)),
                ('date_recette', models.DateField(auto_now_add=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_mis_a_jour', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
