# Generated by Django 6.0.1 on 2026-02-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='date_recette',
            field=models.DateField(),
        ),
    ]
