# Generated by Django 6.0.1 on 2026-02-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0002_alter_recette_date_recette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='date_creation',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='date_mis_a_jour',
            field=models.DateField(auto_now=True),
        ),
    ]
