# Generated by Django 6.0.1 on 2026-02-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0003_alter_recette_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recette',
            options={'verbose_name': 'Recette', 'verbose_name_plural': 'Recettes'},
        ),
        migrations.AlterField(
            model_name='recette',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='date_mis_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
