# Generated by Django 6.0.1 on 2026-02-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0004_alter_recette_options_alter_recette_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='id',
        ),
        migrations.AlterField(
            model_name='recette',
            name='immatriculation',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
